plugins {
    alias(libs.plugins.androlabs.jvm.library)
}

description = "Public and internal 'core' Gradle APIs with implementation"

dependencies {
    implementation(project(":build-tools:base-services"))
    implementation(project(":build-tools:base-services-groovy"))
    implementation(project(":build-tools:gradle-build-operations"))
    implementation(project(":build-tools:enterprise-operations"))
    implementation(project(":build-tools:functional"))
    implementation(project(":build-tools:messaging"))
    implementation(project(":build-tools:logging"))
    implementation(project(":build-tools:problems"))
    implementation(project(":build-tools:resources"))
    implementation(project(":build-tools:cli"))
    implementation(project(":build-tools:build-option"))
    implementation(project(":build-tools:native"))
    implementation(project(":build-tools:model-core"))
    implementation(project(":build-tools:persistent-cache"))
    implementation(project(":build-tools:build-cache"))
    implementation(project(":build-tools:gradle-core-api"))
    implementation(project(":build-tools:files"))
    implementation(project(":build-tools:file-temp"))
    implementation(project(":build-tools:file-collections"))
    implementation(project(":build-tools:process-services"))
    implementation(project(":build-tools:jvm-services"))
    implementation(project(":build-tools:model-groovy"))
    implementation(project(":build-tools:snapshots"))
    implementation(project(":build-tools:file-watching"))
    implementation(project(":build-tools:execution"))
    implementation(project(":build-tools:worker-processes"))
    implementation(project(":build-tools:normalization-java"))
    implementation(project(":build-tools:wrapper-shared"))
    implementation(project(":build-tools:internal-instrumentation-api"))

    implementation("org.tomlj:tomlj:1.1.0")

    implementation(libs.ant)
    implementation(libs.asm)
    implementation(libs.asm.commons)
    implementation(libs.asm.tree)
    implementation(libs.apache.commons.compress)
    implementation(libs.apache.commons.lang3)
    implementation(libs.commons.io)
    implementation(libs.fastutil)
    implementation(libs.groovy)
    implementation(libs.groovy.ant)
    implementation(libs.groovy.json)
    implementation(libs.groovy.templates)
    implementation(libs.groovy.xml)
    implementation(libs.guava)
    implementation(libs.javax.inject)
    implementation(libs.native.platform)
    implementation(libs.slf4j)
}